name: habitera
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  path_provider: ^2.0.15
  google_fonts: ^6.2.1
  intl: ^0.20.1
  go_router: ^17.0.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  isar_generator: ^3.1.0+1


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
